# This is an example of a parameters file
# It is written according to the YAML-convention (www.yaml.org) and is checked by the code for consistency.
# Three types of parameters are possible and reflected in the structure of the document:
#
# Parameter category:
#   Setting Name: <value>
#
# The three parameter categories are:
# - setting: Setting to use for preprocessing and class specific settings. if no <value> is specified, the value for
#   this setting is set to None.
# - featureClass: Feature class to enable, <value> is list of strings representing enabled features. If no <value> is
#   specified or <value> is an empty list ('[]'), all features for this class are enabled.
# - imageType: image types to calculate features on. <value> is custom kwarg settings (dictionary). if <value> is an
#   empty dictionary ('{}'), no custom settings are added for this input image.
#
# Some parameters have a limited list of possible values. Where this is the case, possible values are listed in the
# package documentation

# Settings to use, possible settings are listed in the documentation (section "Customizing the extraction").
setting:
  # Interpolation to isotropic voxel spacing
  resampledPixelSpacing: [1,1,1] # Voxel resampling specified as [x, y, z]
  interpolator: 'sitkBSpline' # Sets interpolator to use for resampling
  correctMask: True # Resample the mask to the image geometry 
  # Discretization
  binCount: 50 # Number of histogram bins
  label: 1 # Label value of Region of Interest (ROI) 
  
# Image types to use: "Original" for unfiltered image, for possible filters, see documentation.
imageType:
  Original: {} # for dictionaries / mappings, None values are not allowed, '{}' is interpreted as an empty dictionary

# Featureclasses, from which features must be calculated. If a featureclass is not mentioned, no features are calculated
# for that class. Otherwise, the specified features are calculated, or, if none are specified, all are calculated (excluding redundant/deprecated features).
featureClass:
  shape: # 14 total: Compactness 1, Compactness 2, and Spherical Disproportion excluded (redundant)
  firstorder: # 18 total: Standard Deviation excluded (not present in IBSI feature definitions, correlated with variance)
  glcm:  # 24 total
  glrlm: # 16 total
  glszm: # 16 total
  gldm: # 14 total
  ngtdm: # 5 total